default_agent: climate_core
agents:
  climate_core:
    name: climate_core
    entrypoint: climate_runtime.py
    platform: linux/arm64
    container_runtime: none
    aws:
      execution_role: arn:aws:iam::117982239532:role/AmazonBedrockAgentCoreSDKRuntime-ap-southeast-2-3f0f7d78c6
      execution_role_auto_create: false
      account: '117982239532'
      region: ap-southeast-2
      ecr_repository: 117982239532.dkr.ecr.ap-southeast-2.amazonaws.com/bedrock-agentcore-climate_core
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: climate_core-7Zp6WKHpg4
      agent_arn: arn:aws:bedrock-agentcore:ap-southeast-2:117982239532:runtime/climate_core-7Zp6WKHpg4
      agent_session_id: 2268b98b-d599-4cf9-9b72-0f295a64cbff
    codebuild:
      project_name: bedrock-agentcore-climate_core-builder
      execution_role: arn:aws:iam::117982239532:role/AmazonBedrockAgentCoreSDKCodeBuild-ap-southeast-2-3f0f7d78c6
      source_bucket: bedrock-agentcore-codebuild-sources-117982239532-ap-southeast-2
    authorizer_configuration: null
    oauth_configuration: null
