import { Paper, Text, Stack, Group, Progress, RingProgress, Button } from '@mantine/core';
import { IconBolt, IconLeaf, IconCurrencyDollar, IconTrendingUp } from '@tabler/icons-react';

// Energy Status Card - Generated by AI
export function EnergyStatusCard({ data }: { data: any }) {
  return (
    <Paper p="md" style={{ background: '#0f1012', border: '1px solid #2C2E33' }}>
      <Stack gap="md">
        <Text size="sm" fw={600} c="white">
          Current Energy Status
        </Text>
        <Group grow>
          <Stack gap={4}>
            <Group gap={4}>
              <IconBolt size={16} color="#2F9E44" />
              <Text size="xs" c="dimmed">Consumption</Text>
            </Group>
            <Text size="xl" fw={700} c="white">
              {data.consumption} kWh
            </Text>
          </Stack>
          <Stack gap={4}>
            <Group gap={4}>
              <IconTrendingUp size={16} color="#2F9E44" />
              <Text size="xs" c="dimmed">Efficiency</Text>
            </Group>
            <Text size="xl" fw={700} c="#2F9E44">
              {data.efficiency}%
            </Text>
          </Stack>
        </Group>
        <Progress value={data.efficiency} color="green" size="md" />
      </Stack>
    </Paper>
  );
}

// Cost Savings Card - Generated by AI
export function CostSavingsCard({ data }: { data: any }) {
  return (
    <Paper p="md" style={{ background: '#0f1012', border: '1px solid #2C2E33' }}>
      <Stack gap="md">
        <Group gap={4}>
          <IconCurrencyDollar size={20} color="#2F9E44" />
          <Text size="sm" fw={600} c="white">
            Cost Savings
          </Text>
        </Group>
        <Group justify="space-between">
          <div>
            <Text size="xs" c="dimmed">Today</Text>
            <Text size="2rem" fw={700} c="#2F9E44" lh={1}>
              ${data.today}
            </Text>
          </div>
          <div>
            <Text size="xs" c="dimmed">This Month</Text>
            <Text size="xl" fw={600} c="white">
              ${data.month}
            </Text>
          </div>
        </Group>
      </Stack>
    </Paper>
  );
}

// Carbon Impact Card - Generated by AI
export function CarbonImpactCard({ data }: { data: any }) {
  return (
    <Paper p="md" style={{ background: '#0f1012', border: '1px solid #2C2E33' }}>
      <Stack gap="md">
        <Group gap={4}>
          <IconLeaf size={20} color="#2F9E44" />
          <Text size="sm" fw={600} c="white">
            Carbon Reduction
          </Text>
        </Group>
        <Group justify="center">
          <RingProgress
            size={120}
            thickness={12}
            sections={[{ value: (data.reduced / data.baseline) * 100, color: 'green' }]}
            label={
              <Stack gap={0} align="center">
                <Text size="xl" fw={700} c="white" lh={1}>
                  {data.reduced}
                </Text>
                <Text size="xs" c="dimmed">
                  kg CO₂
                </Text>
              </Stack>
            }
          />
        </Group>
        <Text size="xs" c="dimmed" ta="center">
          Equivalent to {data.carKm} km of driving avoided
        </Text>
      </Stack>
    </Paper>
  );
}

// Optimization Action Card - Generated by AI
export function OptimizationActionCard({ data }: { data: any }) {
  return (
    <Paper p="md" style={{ background: 'rgba(47, 158, 68, 0.1)', border: '1px solid rgba(47, 158, 68, 0.3)' }}>
      <Stack gap="md">
        <Text size="sm" fw={600} c="white">
          💡 Optimization Opportunity
        </Text>
        <Text size="sm" c="white">
          {data.description}
        </Text>
        <Group justify="space-between">
          <div>
            <Text size="xs" c="dimmed">Potential Savings</Text>
            <Text size="lg" fw={700} c="#2F9E44">
              ${data.savings}/month
            </Text>
          </div>
          <Button size="sm" color="green" variant="light">
            Apply Now
          </Button>
        </Group>
      </Stack>
    </Paper>
  );
}

// AWS Spot Window Card - Generated by AI
export function SpotWindowCard({ data }: { data: any }) {
  return (
    <Paper p="md" style={{ background: '#0f1012', border: '1px solid #2C2E33' }}>
      <Stack gap="sm">
        <Group justify="space-between">
          <Text size="sm" fw={600} c="white">
            Optimal Compute Window
          </Text>
          <Text size="sm" fw={700} c="#2F9E44">
            {data.renewable}% Renewable
          </Text>
        </Group>
        <Text size="lg" fw={600} c="white">
          {data.timeWindow}
        </Text>
        <Group grow>
          <Stack gap={4}>
            <Text size="xs" c="dimmed">Spot Price</Text>
            <Text size="sm" fw={600} c="white">${data.spotPrice}</Text>
          </Stack>
          <Stack gap={4}>
            <Text size="xs" c="dimmed">Savings</Text>
            <Text size="sm" fw={600} c="#2F9E44">{data.savings}%</Text>
          </Stack>
        </Group>
        <Text size="xs" c="dimmed">
          {data.recommendation}
        </Text>
      </Stack>
    </Paper>
  );
}

// Quick Metrics Grid - Generated by AI
export function QuickMetricsGrid({ data }: { data: any }) {
  return (
    <Stack gap="xs">
      {data.metrics.map((metric: any, i: number) => (
        <Group key={i} justify="space-between" p="sm" style={{ background: '#0f1012', borderRadius: 4 }}>
          <Text size="sm" c="dimmed">{metric.label}</Text>
          <Text size="sm" fw={700} c={metric.positive ? '#2F9E44' : 'white'}>
            {metric.value}
          </Text>
        </Group>
      ))}
    </Stack>
  );
}
